# Generated by Django 5.2.8 on 2025-12-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_loginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('PARK', 'Park'), ('MUSEUM', 'Museum'), ('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('MALL', 'Mall'), ('LAKE', 'Lake'), ('STREET_FOOD', 'Street Food'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('average_rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='travel.place')),
                ('traveler', models.ForeignKey(limit_choices_to={'role': 'TRAVELER'}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to='accounts.useraccount')),
            ],
            options={
                'unique_together': {('traveler', 'place')},
            },
        ),
    ]
