# Generated by Django 5.2.8 on 2025-12-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginlog'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('title', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel.place')),
                ('traveler', models.ForeignKey(limit_choices_to={'role': 'TRAVELER'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.useraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
