# Generated by Django 5.2.8 on 2025-12-04 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_area_place_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='merchant',
        ),
        migrations.AlterField(
            model_name='place',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='travel.area'),
        ),
    ]
