# Generated by Django 5.2.8 on 2025-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_place_merchant_alter_place_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('PARK', 'Park'), ('MUSEUM', 'Museum'), ('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('STREET_FOOD', 'Street Food'), ('FAST_FOOD', 'Fast Food'), ('BAKERY', 'Bakery'), ('MALL', 'Mall'), ('SHOP', 'Shop'), ('LOCAL_MARKET', 'Local Market'), ('SUPERMARKET', 'Supermarket'), ('HISTORICAL_SITE', 'Historical Site'), ('LANDMARK', 'Landmark'), ('LAKE', 'Lake'), ('BEACH', 'Beach'), ('ZOO', 'Zoo'), ('CINEMA', 'Cinema'), ('AMUSEMENT_PARK', 'Amusement Park'), ('SPORTS_COMPLEX', 'Sports Complex'), ('HOTEL', 'Hotel'), ('GUEST_HOUSE', 'Guest House'), ('TRANSPORT', 'Transport Hub'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
