# Generated by Django 5.2.8 on 2025-12-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_adminprofile_area'),
        ('travel', '0005_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='accounts.merchantprofile'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('PARK', 'Park'), ('MUSEUM', 'Museum'), ('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('STREET_FOOD', 'Street Food'), ('FAST_FOOD', 'Fast Food'), ('BAKERY', 'Bakery'), ('MALL', 'Mall'), ('SHOP', 'Shop'), ('LOCAL_MARKET', 'Local Market'), ('SUPERMARKET', 'Supermarket'), ('HISTORICAL_SITE', 'Historical Site'), ('LANDMARK', 'Landmark'), ('LAKE', 'Lake'), ('BEACH', 'Beach'), ('ZOO', 'Zoo'), ('CINEMA', 'Cinema'), ('AMUSEMENT_PARK', 'Amusement Park'), ('SPORTS_COMPLEX', 'Sports Complex'), ('HOTEL', 'Hotel'), ('GUEST_HOUSE', 'Guest House'), ('TRANSPORT', 'Transport Hub'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
