# Generated by Django 6.0 on 2025-12-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_place_owner_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
