# Generated by Django 6.0 on 2025-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_place_closing_time_place_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
