# Generated by Django 6.0 on 2025-12-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_remove_place_image_url_place_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
