# Generated by Django 6.0 on 2025-12-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_remove_place_image_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, max_length=100000, null=True),
        ),
    ]
