# Generated by Django 5.2.8 on 2025-11-27 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_merchantprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('area', models.CharField(max_length=200)),
                ('post_type', models.CharField(choices=[('PRICE_ALERT', 'Price Alert'), ('TRAFFIC_UPDATE', 'Traffic Update'), ('FOOD_TIP', 'Food Tip')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='posts.post')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='accounts.useraccount')),
            ],
        ),
    ]
