# Generated by Django 5.2.8 on 2025-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_historic', models.BooleanField(default=False)),
                ('is_residential', models.BooleanField(default=False)),
                ('is_commercial', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('community_post_count', models.PositiveIntegerField(default=0)),
                ('best_time_start', models.TimeField(blank=True, null=True)),
                ('best_time_end', models.TimeField(blank=True, null=True)),
                ('avoid_time_start', models.TimeField(blank=True, null=True)),
                ('avoid_time_end', models.TimeField(blank=True, null=True)),
                ('avoid_reason', models.CharField(blank=True, max_length=200)),
                ('emergency_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
