# Generated by Django 5.2.8 on 2025-11-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
    ]
