# Generated by Django 5.2.8 on 2025-11-28 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('ATM', 'ATM'), ('BANK', 'Bank'), ('PHARMACY', 'Pharmacy'), ('POLICE', 'Police Station'), ('FIRE', 'Fire Station'), ('OTHER', 'Other')], max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('operating_hours', models.CharField(blank=True, max_length=100)),
                ('is_24_7', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='locations.area')),
            ],
            options={
                'ordering': ['service_type', 'name'],
            },
        ),
    ]
