# Generated by Django 5.2.8 on 2025-11-28 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_merchantprofile_closing_time_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('place_type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('SHOP', 'Shop'), ('MALL', 'Mall'), ('LANDMARK', 'Landmark'), ('PARK', 'Park'), ('MOSQUE', 'Mosque'), ('MARKET', 'Market'), ('STREET_FOOD', 'Street Food Spot'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('address', models.TextField(blank=True)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='locations.area')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='accounts.merchantprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to='accounts.useraccount')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'place')},
            },
        ),
    ]
