# Generated by Django 5.2.8 on 2025-11-27 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='business_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_merchants', to='accounts.useraccount'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='years_in_business',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='years_in_area',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
