# Generated by Django 5.2.8 on 2025-12-04 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginlog'),
        ("travel", "0004_remove_place_merchant_alter_place_area"),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profiles', to='travel.area'),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='business_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_profiles', to='travel.area'),
        ),
        migrations.AlterField(
            model_name='travelerprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traveler_profiles', to='travel.area'),
        ),
    ]
