# Generated by Django 5.2.8 on 2025-12-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merchantprofile_closing_time_alter_adminprofile_area_and_more'),
        ('travel', '0004_remove_place_merchant_alter_place_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profiles', to='travel.area'),
        ),
        migrations.CreateModel(
            name='MerchantVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to='accounts.merchantprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_verifications', to='accounts.useraccount')),
            ],
        ),
    ]
