# Generated by Django 5.2.8 on 2025-12-06 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merchantprofile_address_and_more'),
        ('travel', '0004_remove_place_merchant_alter_place_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profile', to='travel.area'),
        ),
    ]
