# Generated by Django 6.0 on 2025-12-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_adminprofile_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('TRAVELER', 'Traveler'), ('MERCHANT', 'Merchant'), ('ADMIN', 'Admin')], default='TRAVELER', max_length=20),
        ),
    ]
