# Generated by Django 5.2.8 on 2025-12-13 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_community', models.BooleanField(default=True)),
                ('notify_chat', models.BooleanField(default=True)),
                ('notify_merchant_updates', models.BooleanField(default=True)),
                ('show_public_username', models.BooleanField(default=True)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.useraccount')),
            ],
        ),
    ]
