# Generated by Django 5.2.8 on 2025-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_merchantprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='merchant_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('SHOP', 'Shop'), ('MALL', 'Mall'), ('SERVICE', 'Service'), ('CAFE', 'Cafe'), ('STREET_FOOD', 'Street Food'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
